title: Dhrumel Shah # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Scientist 
  <br><br>
  Experience: 3yrs at Deloitte-USI and DXC Technology
  <br><br>
  Student at Queen's University
  <br><br>
  Program: Master of Management in Artificial Intelligence
  <br><br>
  Location: Toronto, ON
  <br><br>
  <a href="https://www.linkedin.com/in/dhrumelshah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
