title: Dhrumel Shah # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>Data Scientist</b> 
  <br><br>
  Experience: 3 years
  <br><br>
  Past Companies: Deloitte-USI, DXC Technology
  <br><br>
  Education: 
  - Master of Management in Artificial Intelligence at Queen's University
  - Bachelor of Science in Computer Science at Florida International University
  <br><br>
  Current Location: Toronto, ON
  <br><br>
  <a href="https://www.linkedin.com/in/dhrumelshah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
