title: Dhrumel Shah # your name (or website title) here
logo: "/images/linkedin photo.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Toronto, ON
  <br><br>
  Master of Management in Artificial Intelligence at Queen's University (2021-2022)
  <br><br>
  <a href="https://www.linkedin.com/in/dhrumelshah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
